export const defaultConfig = {
    input: {
        icon: 'ic:baseline-input',
        type: 'input',
        name: 'input',
        label: '文本框',
        disabled: false,
        allowClear: true,
        inputType: 'text',
        maxlength: 100,
    },
    textarea: {
        icon: 'bi:textarea-t',
        type: 'textarea',
        name: 'textarea',
        label: '文本域',
        allowClear: false,
        disabled: false,
        maxlength: 1000,
    },
    number: {
        icon: 'clarity:number-list-line',
        type: 'number',
        name: 'number',
        label: '数字进步器',
        disabled: false,
    },
    select: {
        icon: 'bx:bx-select-multiple',
        type: 'select',
        name: 'select',
        label: '下拉选',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: 'select',
        mode: 'default',
        maxTagCount: 1,
        valueKey: 'id',
        labelKey: 'name',
    },
    treeselect: {
        icon: 'carbon:tree-view-alt',
        type: 'treeselect',
        name: 'treeselect',
        label: '下拉树',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        mode: 'multiple',
        valueKey: 'id',
        labelKey: 'name',
    },
    cascader: {
        icon: 'fluent:text-bullet-list-tree-16-filled',
        type: 'cascader',
        name: 'cascader',
        label: '级联选择器',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        valueKey: 'id',
        labelKey: 'name',
    },
    timepicker: {
        icon: 'ant-design:field-time-outlined',
        type: 'timepicker',
        name: 'timepicker',
        label: '时间选择器',
        disabled: false,
        allowClear: true,
        format: '',
        valueFormat: 'HH:mm:ss',
    },
    datepicker: {
        icon: 'healthicons:i-schedule-school-date-time',
        type: 'datepicker',
        name: 'datepicker',
        label: '日期选择器',
        disabled: false,
        allowClear: true,
        mode: 'time',
        showTime: true,
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
    },
    rangepicker: {
        icon: 'bi:calendar-range',
        type: 'rangepicker',
        name: 'rangepicker',
        label: '时间范围选择器',
        disabled: false,
        allowClear: true,
        showTime: true,
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
    },
    checkbox: {
        icon: 'fluent:checkbox-checked-sync-20-regular',
        type: 'checkbox',
        name: 'checkbox',
        label: '多选框',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        valueKey: 'id',
        labelKey: 'name',
    },
    radio: {
        icon: 'eva:radio-button-on-fill',
        type: 'radio',
        name: 'radio',
        label: '单选框',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        valueKey: 'id',
        labelKey: 'name',
    },
    divider: {
        icon: 'radix-icons:divider-horizontal',
        type: 'divider',
        name: 'divider',
        label: '分割线',
        orientation: 'left',
    },
    input2: {
        icon: 'ic:baseline-input',
        type: 'input',
        name: 'input',
        label: '文本框',
        disabled: false,
        allowClear: true,
        inputType: 'text',
        maxlength: 100,
    },
    textarea2: {
        icon: 'bi:textarea-t',
        type: 'textarea',
        name: 'textarea',
        label: '文本域',
        allowClear: false,
        disabled: false,
        maxlength: 1000,
    },
    number2: {
        icon: 'clarity:number-list-line',
        type: 'number',
        name: 'number',
        label: '数字进步器',
        disabled: false,
    },
    select2: {
        icon: 'bx:bx-select-multiple',
        type: 'select',
        name: 'select',
        label: '下拉选',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: 'select',
        mode: 'default',
        maxTagCount: 1,
        valueKey: 'id',
        labelKey: 'name',
    },
    treeselect2: {
        icon: 'carbon:tree-view-alt',
        type: 'treeselect',
        name: 'treeselect',
        label: '下拉树',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        mode: 'multiple',
        valueKey: 'id',
        labelKey: 'name',
    },
    cascader2: {
        icon: 'fluent:text-bullet-list-tree-16-filled',
        type: 'cascader',
        name: 'cascader',
        label: '级联选择器',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        valueKey: 'id',
        labelKey: 'name',
    },
    timepicker2: {
        icon: 'ant-design:field-time-outlined',
        type: 'timepicker',
        name: 'timepicker',
        label: '时间选择器',
        disabled: false,
        allowClear: true,
        format: '',
        valueFormat: 'HH:mm:ss',
    },
    datepicker2: {
        icon: 'healthicons:i-schedule-school-date-time',
        type: 'datepicker',
        name: 'datepicker',
        label: '日期选择器',
        disabled: false,
        allowClear: true,
        mode: 'time',
        showTime: true,
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
    },
    rangepicker2: {
        icon: 'bi:calendar-range',
        type: 'rangepicker',
        name: 'rangepicker',
        label: '时间范围选择器',
        disabled: false,
        allowClear: true,
        showTime: true,
        valueFormat: 'YYYY-MM-DD HH:mm:ss',
    },
    checkbox2: {
        icon: 'fluent:checkbox-checked-sync-20-regular',
        type: 'checkbox',
        name: 'checkbox',
        label: '多选框',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        valueKey: 'id',
        labelKey: 'name',
    },
    radio2: {
        icon: 'eva:radio-button-on-fill',
        type: 'radio',
        name: 'radio',
        label: '单选框',
        disabled: false,
        allowClear: true,
        datasourceType: 'local',
        datasource: '',
        valueKey: 'id',
        labelKey: 'name',
    },
    divider2: {
        icon: 'radix-icons:divider-horizontal',
        type: 'divider',
        name: 'divider',
        label: '分割线',
        orientation: 'left',
    }
};

export const defaultRules = {
    input: [{
        required: false,
        message: '请填写必填项',
        type: 'string'
    }],
    textarea: [{
        required: false,
        message: '请填写必填项',
        type: 'string'
    }],
    number: [{
        required: false,
        message: '请填写必填项',
        type: 'number'
    }],
    select: [{
        required: false,
        message: '请选择必填项',
        type: 'array'
    }],
    treeselect: [{
        required: false,
        message: '请选择必填项',
        type: 'array'
    }],
    cascader: [{
        required: false,
        message: '请选择必填项',
        type: 'array'
    }],
    datepicker: [{
        required: false,
        message: '请选择必填项',
        type: 'string'
    }],
    rangepicker: [{
        required: false,
        message: '请选择必填项',
        type: 'array'
    }],
    timepicker: [{
        required: false,
        message: '请选择必填项',
        type: 'string'
    }],
    checkbox: [{
        required: false,
        message: '请选择必填项',
        type: 'array'
    }],
    radio: [{
        required: false,
        message: '请选择必填项',
        type: 'string'
    }],
}

export const defaultValue = {
    input: '',
    textarea: '',
    select: undefined,
    treeselect: [],
    cascader: [],
    datepicker: '',
    rangepicker: [],
    timepicker: '',
}

export const defaultPlaceholder = {
    input: '请填写',
    textarea: '请填写',
    select: '请选择',
    treeselect: '请选择',
    cascader: '请选择',
    datepicker: '请选择',
    rangepicker: '请选择',
    timepicker: '请选择',
}
